---
title: "Fabian Markdown"
output: html_document
date: "2024-02-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Funktion, um verschiedene Seperatoren richtig zu identifizieren 
Dieser Abschnitt muss noch richtig eingebaut werden in den Code unten, er ist noch nicht implementiert - nur zur Erinnerung 


```{r}
#Hier eigenen Pfad für Dateien eingeben 
folder_path <- "./Einzelteil"

#Vektor, wo die für uns relevanten Einzelteile aufgelistet sind 
our_txt <- c("Einzelteil_T31.txt","Einzelteil_T34.txt","Einzelteil_T35.txt","Einzelteil_T36.txt","Einzelteil_T39.txt")

our_csv <- c("Einzelteil_T30.csv","Einzelteil_T31.txt","Einzelteil_T32.csv","Einzelteil_T33.csv","Einzelteil_T34.txt","Einzelteil_T35.txt","Einzelteil_T36.txt","Einzelteil_T37.csv","Einzelteil_T38.csv","Einzelteil_T39.txt","Einzelteil_T40.csv")

#Dateien mit Semikolon als Seperator
semiko_sep <- c("Einzelteil_T32.csv","Einzelteil_T40.csv")


#Erzeugung leere Liste für die Einzelteile
list_of_parts <- list()


```



```{r}

#Erstellung Vektor mit Dokumentennamen 
file_list_txt <- list.files(folder_path,pattern = "*.txt")

#Textfiles einlesen und in .csv exportieren 
for(file in file_list_txt){
  if(file %in% our_txt){
    
    #Valentin Abschnitt zum einlesen der .txt 
    
  }


```



```{r}

#Erstellung Vektor mit Dokumentennamen 
file_list_csv <- list.files(folder_path,pattern="*.csv")

for(file in file_list_csv){
  if(file %in% our_csv){
    
      full_path <- paste0(folder_path, "/", file)
  
    if(file.exists(full_path)){
      if(file %in% semiko_sep){
        
        list_of_parts[[file]] <- read.csv2(full_path, sep=";", header=T,dec=",")
        
      }else{
       list_of_parts[[file]] <- read.csv2(full_path, sep=",", dec = "." ,header=T)  
        }
      
    }
    
  }else{
      
      print(paste(file,"gehört nicht zu den untersuchten .csv Daten"))
      next
    }
  
}
  
}

```




#Versuch Einzelteil T30 zu reparieren 
```{r eval=FALSE, include=FALSE}
#Spaltennamen herausfinden 
names(T30)

#Doppelte Spalten zu einer zusammenführen 
ID_col <- c(T30$ID_T30.x,T30$ID_T30.y,T30$ID_T30)

#NA entfernen aus Spalte - später mit names(gesamt)
ID_col <- na.omit(ID_col)




```

