---
title: "Valentin Markdown"
output: html_document
date: "2024-02-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("tidyr")
library(tidyr)
library(dplyr)
library(stringr)
library(purrr)
```


```{r setup, include=FALSE}
file_path <- 'Fahrzeug/Fahrzeug/Bestandteile_Fahrzeuge_OEM1_Typ11.csv'
# Read the CSV file
data <- read.csv(file_path, sep=';', header=TRUE)

# data_karosserie <- data %>%
#   group_by(Grouped_Column = substr(ID_Karosserie, 1, 2)) %>%
#   summarize(Count = n(),
#             FirstValue = first(ID_Karosserie))
# data_karosserie

summarize_and_print <- function(data, columns) {
  for (col in columns) {
    result <- data %>%
      group_by(Grouped_Column = str_extract(!!sym(col), "^[^-]+")) %>%
      summarise(Count = n(),
                FirstValue = first(!!sym(col)))
    
    cat("\nSummary for column:", col, "\n")
    print(result, row.names = FALSE)
  }
}

columns_to_summarize <- c("ID_Karosserie", "ID_Schaltung", "ID_Sitze", "ID_Motor")

# Call the function
summarize_and_print(data, columns_to_summarize)


file_path <- 'Komponente/Komponente/Bestandteile_Komponente_K4.csv'
# Read the CSV fil
data <- read.csv(file_path, sep=';', header=TRUE)

columns_to_summarize <- c("ID_Karosserie", "ID_Schaltung", "ID_Sitze", "ID_Motor")

# Call the function
summarize_and_print(data, columns_to_summarize)
```

Import data (should be Fabian is working on it)
```{r}
file_path <- 'Einzelteile/Einzelteil_T30.csv'
# Read the CSV fil
data <- read.csv(file_path, header=TRUE)

```


Function to delete .x and .y columns and add them below the original column
```{r}
cleaner_einzelteile <- function(data) {
  data$X <- NULL
  data$X1 <- NULL
  original_columns <- colnames(data)[!grepl("\\.x$|\\.y$", colnames(data))]
  concatenated_data <- data.frame(matrix(nrow = 3 * nrow(data), ncol = length(original_columns)))
  if (ncol(data) == 7) {
    column_vector <- colnames(data)
    column_vector <- na.omit(column_vector)
    return(data)
  }
  else if (ncol(data) == 14) {
    ID_T30 <- c(data$T30, data$ID_T30.x)
    column_vector <- colnames(data)
    column_vector <- na.omit(column_vector)
  }
  else if (ncol(data) == 21){
    for (col in original_columns) {
      concatenated_data[[col]] <- c(data[[col]], data[[paste0(col, ".x")]], data[[paste0(col, ".y")]])
    }
    return(concatenated_data)
  }
}
cleandata <- cleaner_einzelteile(data)
```

Remove NA's (this should be generalized and added to main function).
```{r}
cleandata <- cleandata[!is.na(cleandata$ID_T30), ]

#Delete columns only containing NAs
cleandata <- cleandata[, colSums(is.na(cleandata)) != nrow(cleandata)]
```

